export interface GetBody {
    poster_path: string | null,
    adult: boolean,
    overview: string,
    release_date: string,
    genres: any[],
    id: number,
    original_title: string,
    original_language: string,
    title: string,
    backdrop_path: string | null,
    popularity: number,
    vote_count: number,
    video: boolean,
    vote_average: number,
    belongs_to_collection: any,
    budget: number,
    homepage: string,
    imdb_id: string,
    tagline: string,
    status: string,
    production_companies: any[],
    production_countries: any[],
    spoken_languages: any[]
}